language: node_js
node_js:
- stable
deploy:
  provider: "npm"
  email: "tzachbonfil@gmail.com"
  api_key:
    secure: ZfS92XMbSLs1wjIYlamC8gtXmwrUgFvxXteyRbbIYS1GoCiBttWqjhArsTnsBn5BJnT8670ayDMLN8/AZM722gxPYGQA6NFznbvMm/USDHbQdNO4VMlbhZQhkCWBkVntwvP1pc4V8Y9Xa9dwC/F9VU6Ipz7VsOi8azqrcaCmcdcISyNDsiV60g+q+yBuMK7BijYMRe12tEHCfALd7modDNOsqnGkd9DAT3PcvwqcVA6C28fHAmq9iJc2Ovq2mXzMnSmBdrveb9NP8iqrjlrVQY2s46RoBvkjabP5V210xRwxPsHXEnMlk5UKaBV9q3ZZ+c2o52PFjCo+uWgKX7eOMIT790gVJuhvXOMykk/CHXRKXWPTprL97x3T306PtFrKpARPXj/VMMTODsM7i4HD7IQLAA10XT/Tkl5mCUxyMn6DVqchkeKfhRyD6MbfGSF1BltZhSQ94sqBJL5mEQWEcbbuRnGwVMeMA05luhIKl0aB74UjMotGR6PqTRD4+maJztxv4afWQFt/qX51z0QQNXbxydhWb65Je88Wt3e9U/UBRiFT8HQUm+VwNyACI0sWa7IgIxJ0j1gvRh4hF6wsxes4bJIy2G4/mgc/MZRRycP0qj7MczgSJVIpSEVEG1FSN/n5JTvKvzS1i3D6k3bxgk343IJFHkuT7kaE0Mxwg8E=
